includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/fd_align.yaml
  - backbones/clip_vit.yaml

backbone:
  name: clip_vit32
  kwargs:

classifier:
  name: CLIP_context
  kwargs:
    train_batch_size_per_gpu: 4
    val_batch_size_per_gpu: 8
    test_batch_size_per_gpu: 8